//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string RIGHT_WRIST = "right_wrist";
        
        public const string RIGHT_THUMB = "right_thumb";
        
        public const string RIGHT_INDEX = "right_index";
        
        public const string RIGHT_MIDDLE = "right_middle";
        
        public const string RIGHT_RING = "right_ring";
        
        public const string RIGHT_PINKY = "right_pinky";
        
        public const string LEFT_WRIST = "left_wrist";
        
        public const string LEFT_THUMB = "left_thumb";
        
        public const string LEFT_INDEX = "left_index";
        
        public const string LEFT_MIDDLE = "left_middle";
        
        public const string LEFT_RING = "left_ring";
        
        public const string LEFT_PINKY = "left_pinky";
    }
}
